ShafiuddinSarkariSchool/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShafiuddinSarkariSchool.Context;
using ShafiuddinSarkariSchool.Models;

namespace ShafiuddinSarkariSchool.Controllers
{
    public class AdminController : Controller
    {
        private readonly SchoolDbContext _context;

        public AdminController(SchoolDbContext context)
        {
            _context = context;
        }

        // GET: Admin
        public async Task<IActionResult> Index()
        {
            return View(await _context.tblAdmin.ToListAsync());
        }

        // GET: Admin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblAdmin = await _context.tblAdmin
                .FirstOrDefaultAsync(m => m.AdminId == id);
            if (tblAdmin == null)
            {
                return NotFound();
            }

            return View(tblAdmin);
        }

        // GET: Admin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AdminId,Name,ExamDate,MarksSubmitDate,ResultPublishDate")] tblAdmin tblAdmin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblAdmin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblAdmin);
        }

        // GET: Admin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblAdmin = await _context.tblAdmin.FindAsync(id);
            if (tblAdmin == null)
            {
                return NotFound();
            }
            return View(tblAdmin);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AdminId,Name,ExamDate,MarksSubmitDate,ResultPublishDate")] tblAdmin tblAdmin)
        {
            if (id != tblAdmin.AdminId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblAdmin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblAdminExists(tblAdmin.AdminId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblAdmin);
        }

        // GET: Admin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblAdmin = await _context.tblAdmin
                .FirstOrDefaultAsync(m => m.AdminId == id);
            if (tblAdmin == null)
            {
                return NotFound();
            }

            return View(tblAdmin);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblAdmin = await _context.tblAdmin.FindAsync(id);
            _context.tblAdmin.Remove(tblAdmin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool tblAdminExists(int id)
        {
            return _context.tblAdmin.Any(e => e.AdminId == id);
        }
    }
}

ShafiuddinSarkariSchool/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShafiuddinSarkariSchool.Context;
using ShafiuddinSarkariSchool.Models;

namespace ShafiuddinSarkariSchool.Controllers
{
    public class ClassController : Controller
    {
        private readonly SchoolDbContext _context;

        public ClassController(SchoolDbContext context)
        {
            _context = context;
        }

        // GET: Classe
        public async Task<IActionResult> Index()
        {
            return View(await _context.tblClass.ToListAsync());
        }

        // GET: Classe/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblClass = await _context.tblClass
                .FirstOrDefaultAsync(m => m.ClassId == id);
            if (tblClass == null)
            {
                return NotFound();
            }

            return View(tblClass);
        }

        // GET: Classe/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Classe/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClassId,Name")] tblClass tblClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblClass);
        }

        // GET: Classe/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblClass = await _context.tblClass.FindAsync(id);
            if (tblClass == null)
            {
                return NotFound();
            }
            return View(tblClass);
        }

        // POST: Classe/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClassId,Name")] tblClass tblClass)
        {
            if (id != tblClass.ClassId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblClassExists(tblClass.ClassId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblClass);
        }

        // GET: Classe/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblClass = await _context.tblClass
                .FirstOrDefaultAsync(m => m.ClassId == id);
            if (tblClass == null)
            {
                return NotFound();
            }

            return View(tblClass);
        }

        // POST: Classe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblClass = await _context.tblClass.FindAsync(id);
            _context.tblClass.Remove(tblClass);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool tblClassExists(int id)
        {
            return _context.tblClass.Any(e => e.ClassId == id);
        }
    }
}

ShafiuddinSarkariSchool/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShafiuddinSarkariSchool.Context;
using ShafiuddinSarkariSchool.Models;

namespace ShafiuddinSarkariSchool.Controllers
{
    public class LoginController : Controller
    {
        private readonly SchoolDbContext _context;

        public LoginController(SchoolDbContext context)
        {
            _context = context;
        }

        // GET: Login
        public async Task<IActionResult> Index()
        {
            return View(await _context.tblLogin.ToListAsync());
        }


        public IActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AdminLogin(tblLogin log)
        {
            var test = (from s in _context.tblLogin
                        where s.UserName == log.UserName && s.Password == log.Password && s.UserType == log.UserType
                        select s).FirstOrDefault();
            if (test != null)
            {
                if (test.UserType == "Admin")
                {
                    return RedirectToAction("Index", new { username = test.UserName });
                }
                else if (test.UserType == "Teacher")
                {
                    return RedirectToAction("Create", "Teacher", new { username = test.UserName });
                }
                else if (test.UserType == "Student")
                {
                    return RedirectToAction("Result", "Teacher", new { username = test.UserName });
                }
            }
            else
            {
                ViewBag.msg = "Username or Password or User Type is incorrect";
            }
            return View();
        }

        // GET: Login/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblLogin = await _context.tblLogin
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblLogin == null)
            {
                return NotFound();
            }

            return View(tblLogin);
        }

        // GET: Login/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Login/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,UserType,Password")] tblLogin tblLogin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tblLogin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tblLogin);
        }

        // GET: Login/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblLogin = await _context.tblLogin.FindAsync(id);
            if (tblLogin == null)
            {
                return NotFound();
            }
            return View(tblLogin);
        }

        // POST: Login/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,UserType,Password")] tblLogin tblLogin)
        {
            if (id != tblLogin.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tblLogin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblLoginExists(tblLogin.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tblLogin);
        }

        // GET: Login/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblLogin = await _context.tblLogin
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tblLogin == null)
            {
                return NotFound();
            }

            return View(tblLogin);
        }

        // POST: Login/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblLogin = await _context.tblLogin.FindAsync(id);
            _context.tblLogin.Remove(tblLogin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool tblLoginExists(int id)
        {
            return _context.tblLogin.Any(e => e.Id == id);
        }
    }
}

ShafiuddinSarkariSchool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- Bootstrap CSS -->
    <link href="~/Theme/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="~/Theme/css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="~/Theme/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles -->
    <link href="~/Theme/css/style.css" rel="stylesheet">
    <link href="~/Theme/css/style-responsive.css" rel="stylesheet" />






</head>
<body>

    <!-- container section start -->
    <section id="container" class="">
        <!--header start-->

        <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i> </div>

            </div>

            <!--logo start-->
            <a href="index.html" class="logo"><span class="lite">Admin Panel</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">


                <!-- notificatoin dropdown end-->
            </div>


        </header>
        <!--header end-->
        <!--sidebar start-->

        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu">
                    <li class="">
                        <a class="" href="#">
                            <i class="icon_house_alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>


                    @*<li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon_desktop"></i>
                            <span>Add User</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">

                            <ul class="agile_forms">
                               
                            </ul>



                        </ul>
                    </li>*@


                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon_document_alt"></i>
                            <span>Add References</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            @*<li><a class="" href="form_component.html">Form Elements</a></li>
                                <li><a class="" href="form_validation.html">Form Validation</a></li>*@

                            <li>@Html.ActionLink("Add Medium", "Create", "Medium")</li>
                            <li>@Html.ActionLink("Add Class", "Create", "Class")</li>
                            <li>@Html.ActionLink("Add Subject", "Create", "Subject")</li>

                            <li>@Html.ActionLink("Add Gender", "Create", "Gender")</li>
                            <li>@Html.ActionLink("Add Blood Group", "Create", "BloodGroup")</li>
                            <li>@Html.ActionLink("Add Religion", "Create", "Religion")</li>
                      


                        </ul>
                    </li>

                    @*<li>
                            <a class="" href="widgets.html">
                                <i class="icon_genius"></i>
                                <span>Widgets</span>
                            </a>
                        </li>*@
                    @*<li>
                            <a class="" href="chart-chartjs.html">
                                <i class="icon_piechart"></i>
                                <span>Charts</span>

                            </a>

                        </li>*@

                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon_table"></i>
                            <span>Exam Schedule manage</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            @*<li><a class="" href="basic_table.html">Basic Table</a></li>*@

                            <li>@Html.ActionLink("Exam date mange", "Index", "Admin")</li>
                           







                        </ul>
                    </li>

                    <li class="sub-menu ">
                        <a href="javascript:;" class="">
                            <i class="icon_documents_alt"></i>
                            <span>Report</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">



                            <li>@Html.ActionLink("Student Report", "Index", "Student")</li>













                            @*<li><a class="" href="profile.html">Profile</a></li>
                                <li><a class="" href="login.html"><span>Login Page</span></a></li>
                                <li><a class="active" href="blank.html">Blank Page</a></li>
                                <li><a class="" href="404.html">404 Error</a></li>*@
                        </ul>
                    </li>


                </ul>

                <li>@Html.ActionLink("Log Out", "AdminLogin", "Login")<i class="fa fa-sign-in" aria-hidden="true"></i></li>



                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">

                <!-- page start-->
                @RenderBody()


                <!-- page end-->
            </section>
        </section>
        <!--main content end-->

    </section>
    <!-- container section end -->
    <!-- javascripts -->
    <script src="~/Theme/js/jquery.js"></script>
    <script src="~/Theme/js/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <!-- nice scroll -->
    <script src="~/Theme/js/jquery.scrollTo.min.js"></script>
    <script src="~/Theme/js/jquery.nicescroll.js" type="text/javascript"></script><!--custome script for all page-->
    <script src="~/Theme/js/scripts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

ShafiuddinSarkariSchool/Views/Shared/_StudentLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- Bootstrap CSS -->
    <link href="~/Theme/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="~/Theme/css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="~/Theme/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles -->
    <link href="~/Theme/css/style.css" rel="stylesheet">
    <link href="~/Theme/css/style-responsive.css" rel="stylesheet" />






</head>
<body>

    <!-- container section start -->
    <section id="container" class="">
        <!--header start-->

        <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i> </div>

            </div>

            <!--logo start-->
            <a href="index.html" class="logo"><span class="lite">Student Panel</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">


                <!-- notificatoin dropdown end-->
            </div>


        </header>
        <!--header end-->
        <!--sidebar start-->

        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu">
                    <li class="">
                        <a class="" href="index.html">
                            <i class="icon_house_alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>





                    <li class="sub-menu ">
                        <a href="javascript:;" class="">
                            <i class="icon_documents_alt"></i>
                            <span>Show Result</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">



                            <li>@Html.ActionLink("Result Report", "Index", "Teacher")</li>













                            @*<li><a class="" href="profile.html">Profile</a></li>
                                <li><a class="" href="login.html"><span>Login Page</span></a></li>
                                <li><a class="active" href="blank.html">Blank Page</a></li>
                                <li><a class="" href="404.html">404 Error</a></li>*@
                        </ul>
                    </li>


                </ul>

                <li>@Html.ActionLink("Log Out", "AdminLogin", "Login")<i class="fa fa-sign-in" aria-hidden="true"></i></li>



                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">

                <!-- page start-->
                @RenderBody()


                <!-- page end-->
            </section>
        </section>
        <!--main content end-->

    </section>
    <!-- container section end -->
    <!-- javascripts -->
    <script src="~/Theme/js/jquery.js"></script>
    <script src="~/Theme/js/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <!-- nice scroll -->
    <script src="~/Theme/js/jquery.scrollTo.min.js"></script>
    <script src="~/Theme/js/jquery.nicescroll.js" type="text/javascript"></script><!--custome script for all page-->
    <script src="~/Theme/js/scripts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

ShafiuddinSarkariSchool/Views/Shared/_TeacherLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="img/favicon.png">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <!-- Bootstrap CSS -->
    <link href="~/Theme/css/bootstrap.min.css" rel="stylesheet">
    <!-- bootstrap theme -->
    <link href="~/Theme/css/bootstrap-theme.css" rel="stylesheet">
    <!--external css-->
    <!-- font icon -->
    <link href="~/Theme/css/elegant-icons-style.css" rel="stylesheet" />
    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles -->
    <link href="~/Theme/css/style.css" rel="stylesheet">
    <link href="~/Theme/css/style-responsive.css" rel="stylesheet" />






</head>
<body>

    <!-- container section start -->
    <section id="container" class="">
        <!--header start-->

        <header class="header dark-bg">
            <div class="toggle-nav">
                <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
            </div>

            <!--logo start-->
            <a href="index.html" class="logo"><span class="lite">Teacher Panel</span></a>
            <!--logo end-->

            <div class="nav search-row" id="top_menu">

                </ul>
                <!-- notificatoin dropdown end-->
            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu">
                    <li class="">
                        <a class="" href="index.html">
                            <i class="icon_house_alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>


                    @*<li>
                <a class="" href="widgets.html">
                    <i class="icon_genius"></i>
                    <span>Widgets</span>
                </a>
            </li>*@
                    @*<li>
                <a class="" href="chart-chartjs.html">
                    <i class="icon_piechart"></i>
                    <span>Charts</span>

                </a>

            </li>*@





                    <li class="sub-menu">
                        <a href="javascript:;" class="">
                            <i class="icon_table"></i>
                            <span>Result Publish</span>
                            <span class="menu-arrow arrow_carrot-right"></span>
                        </a>
                        <ul class="sub">
                            @*<li><a class="" href="basic_table.html">Basic Table</a></li>*@
                            <li>@Html.ActionLink("Result Published", "Create", "Teacher")</li>




                        </ul>
                    </li>

                </ul>

                <li>@Html.ActionLink("Log Out", "AdminLogin", "Login")<i class="fa fa-sign-in" aria-hidden="true"></i></li>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <section id="main-content">
            <section class="wrapper">

                <!-- page start-->
                @RenderBody()


                <!-- page end-->
            </section>
        </section>
        <!--main content end-->

    </section>
    <!-- container section end -->
    <!-- javascripts -->
    <script src="~/Theme/js/jquery.js"></script>
    <script src="~/Theme/js/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <!-- nice scroll -->
    <script src="~/Theme/js/jquery.scrollTo.min.js"></script>
    <script src="~/Theme/js/jquery.nicescroll.js" type="text/javascript"></script><!--custome script for all page-->
    <script src="~/Theme/js/scripts.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>